[0m19:03:27.294975 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107fe1970>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10803e600>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10803e2a0>]}


============================== 19:03:27.381011 | 62faccd2-a9c7-4809-9f87-f52d2e4c8db4 ==============================
[0m19:03:27.381011 [info ] [MainThread]: Running with dbt=1.7.8
[0m19:03:27.384627 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': '/Users/kennethchinedu/.dbt', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt test', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m19:03:27.387439 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/kennethchinedu/Desktop/DE/DBT_project/Dbt_airflow_project/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m19:03:27.581865 [debug] [MainThread]: Resource report: {"command_name": "test", "command_wall_clock_time": 0.42915186, "process_user_time": 2.606311, "process_kernel_time": 0.435637, "process_mem_max_rss": "96550912", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m19:03:27.590373 [debug] [MainThread]: Command `dbt test` failed at 19:03:27.586761 after 0.46 seconds
[0m19:03:27.591475 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1071a4e00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107fe1a30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107bba360>]}
[0m19:03:27.602928 [debug] [MainThread]: Flushing usage events
[0m19:15:08.430638 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111935ca0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111996690>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1119963f0>]}


============================== 19:15:08.498036 | c37ceb59-4179-4780-8e97-d6accf628e58 ==============================
[0m19:15:08.498036 [info ] [MainThread]: Running with dbt=1.7.8
[0m19:15:08.499925 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': '/Users/kennethchinedu/.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt run -m stg_orders_items', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m19:15:08.501833 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/kennethchinedu/Desktop/DE/DBT_project/Dbt_airflow_project/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m19:15:08.507486 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.27547562, "process_user_time": 3.274591, "process_kernel_time": 0.559638, "process_mem_max_rss": "92250112", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m19:15:08.511368 [debug] [MainThread]: Command `dbt run` failed at 19:15:08.510583 after 0.28 seconds
[0m19:15:08.513277 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10d03ec90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11153f770>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111996480>]}
[0m19:15:08.516561 [debug] [MainThread]: Flushing usage events
[0m10:29:40.002164 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10a0c0800>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109f1ab10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10a0f2570>]}


============================== 10:29:40.019461 | a0973c61-444f-4b37-a4a1-17900bfafcfd ==============================
[0m10:29:40.019461 [info ] [MainThread]: Running with dbt=1.7.8
[0m10:29:40.020540 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': '/Users/kennethchinedu/.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt run -m src_orders_items', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m10:29:40.021396 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/kennethchinedu/Desktop/DE/DBT_project/Dbt_airflow_project/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m10:29:40.024803 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.14264216, "process_user_time": 2.684173, "process_kernel_time": 0.523292, "process_mem_max_rss": "96575488", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m10:29:40.025767 [debug] [MainThread]: Command `dbt run` failed at 10:29:40.025560 after 0.14 seconds
[0m10:29:40.026308 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1057bac60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1058c71d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10a0c0800>]}
[0m10:29:40.026854 [debug] [MainThread]: Flushing usage events
